// Exp_teeth_base_offset

float $offset = 0.215;

/*rivet_ribbon_teethUp_01_posInfo.parameterU = rivet_ribbon_teethUp_01.parameter_u + $offset;
rivet_ribbon_teethUp_02_posInfo.parameterU = rivet_ribbon_teethUp_02.parameter_u + $offset;
rivet_ribbon_teethUp_03_posInfo.parameterU = rivet_ribbon_teethUp_03.parameter_u + $offset;
rivet_ribbon_teethUp_04_posInfo.parameterU = rivet_ribbon_teethUp_04.parameter_u + $offset;
rivet_ribbon_teethUp_05_posInfo.parameterU = rivet_ribbon_teethUp_05.parameter_u + $offset;*/
rivet_ribbon_teethUp_06_posInfo.parameterU = rivet_ribbon_teethUp_06.parameter_u + $offset;